### ISSUE TITLE
SSO login broken?

### ISSUE THREAD

**Issue by Seraphine725** [the-marenga/sf-api#103]
I have noticed that the SSO login doesn't seem to work properly

my believe is that the password hashing is not working correctly because the hash we currently calculate doesn't match the one the official game client sends to the server

**Comment by the-marenga** [comment]
Very much possible. S&F is currently working on rolling out and then immediately reverting a bunch of changes to auth and requests #96 in general. At this point in time I am not sure if they will revert everything, keep some legacy stuff around, or what they are going to do. This is certainly not a clean update on their side.

I am going to have a look at what they changed for SSO, but since I am not sure if they are reverting/changing their approach for this as well, so I am going to wait like a day or two for things to settle before I push any fixes for this
