### ISSUE TITLE
Data of arena fight xp & items in shop

### ISSUE THREAD

**Issue by AbsolutNixAnDichGeht** [the-marenga/sf-api#16]
Hey, 
thanks for the API, finally I have the courage to look into rust. :D
I have noticed 2 problems so far.

I have not yet found a way to check how many arena battles have already been won today without caching the number myself. 

There is no way to retrieve the individual items from the stores. At least I have searched and tried in vain in gamestate::Shop so far.

**Comment by the-marenga** [comment]
Hey, thanks for the report 😄 

You are absolutely correct in regards to the shop items. Seems like I forgot to change the items array to public and/or have getters for them, when I did some refactoring pre release. I am going to check, if I made the same error elsewhere and fix that within the next few hours. 

I can't recall, if the arena battle count was hard to find/parse, or if I just forgot that. Eitherway, I am going to add that as well, but that might take a bit longer, depending on how annoying the parsing turns out to be.

**Comment by the-marenga** [comment]
I just assume you meant the arena battles, that count for XP (0-10). Pretty sure there is no total battle count, but if I am wrong, let me know. If that is what you meant, both things should be fixed in the newest release. 

As an irrelevant bonus info, the xp battle count was in the upper bits of the player level. It is always fascinating to me, that the S&F devs decided to encode some values as unintuitive as possible.

Anyways, if you find any other errors, or stuff I forgot to parse, feel free to let me know. Otherwise, good luck with your Rust journey 😄
