### ISSUE TITLE
dungeon fight commands missing?

### ISSUE THREAD

**Issue by FildaMil** [the-marenga/sf-api#60]
I couldn't find Shadow world, Twister, Continuous loop of idols and Demon portal fight commands. Not sure if I just don't know where to look or it's missing.

**Comment by the-marenga** [comment]
`Shadow world` - Are you using the newest version? 0.1.3 added the command to fight in the shadow world via `Command::FightShadowDungeon`. 

`Twister, Continuous loop of idols` - The game treats these as normal dungeon, so you can fight these with normal commands.
-  `Continuous loop of idols` - Can be fought by the normal shadow dungeon fight command with continuousloopofidols as the target
-  `Twister` - Can be fought by using the fight light dungeon command with tower as the dungeon. This does not make any sense, but this is somehow what the server wants... I think it makes sense to fix this for the next release and map this behind the scenes, so that fightshadowdungeon(twister) fights in the twister instead. Just noticed this because of you, so thanks for pointing that out

`Demon portal` - Command::PlayerPortalBattle
