### ISSUE TITLE
Hellevator attack?

### ISSUE THREAD

**Issue by FildaMil** [the-marenga/sf-api#64]
Sorry, just want to ask if there is a way to attack in Hellevator. I don't really know how to find out the cmd_name for the custom command.

**Comment by the-marenga** [comment]
Hellevator is currently the part of the API, that is the least finished. I am currently working on overhauling the entire API https://github.com/the-marenga/sf-api/pull/63, so this will be fixed and have examples on how to use it in the next release (< 1 week). 

Up until then, you would have to use the custom command, yes. I just checked and the main "attack" command is:

```Rust
Command::Custom {
    cmd_name: "GroupTournamentBattle".to_string(),
    arguments: vec![1.to_string()],
}
```
with either a 1, or 0 as the argument, where 1 means using a mushroom to atttack.

If you do not want to wait for the next release to get full hellevator support, you could also switch to using my [current working branch](https://github.com/the-marenga/sf-api/tree/array_index) `array_index` in this repo instead of the current release. I will work on getting the hellevator fully working there this night. It's a big work-in-progress update, so using that branch would bring it's own challenges with it though

**Comment by FildaMil** [comment]
Thank you so much! <3
