### ISSUE TITLE
could not find `SimpleSession`

### ISSUE THREAD

**Issue by cilipecos** [the-marenga/sf-api#81]
Hi, im kinda new to this so im sorry if im asking something obvious but I have the latest version 0.1.3 and I cant find SimpleSession (the first example doesn't work for me). 

The error:
"failed to resolve: could not find `SimpleSession` in `sf_api`"
"could not find `SimpleSession` in `sf_api`"

I created a new project (cargo init) and added the sf-api (cargo add sf-api).

![sf1](https://github.com/the-marenga/sf-api/assets/174999526/05a436bf-eb17-4f17-aa4a-b9e1d9695ea0)

[dependencies]
sf-api = "0.1.3"
tokio = { version = "1.38.0", features = ["full"] }

I don't know if I provided enough info, if not please let me know.

**Comment by the-marenga** [comment]
The documentation in this repo is for the current state of development (0.2.0), which includes SimpleSession. 0.1.3 does **not** yet include SimpleSession. You should switch to the (in development) version 0.2.0 from this git repo to use that, instead of the current release. 

You can do that, by changing your sf-api dependency to:

```
sf-api = { git = "https://github.com/the-marenga/sf-api", rev = "79607d2" }
```

Just as a heads up, the last big S&F update from a few days ago broke a few thing and the level of dungeon enemies is wrong currently. Otherwise, the in development version should work. 

As soon, as I get the time to do that, I will fix the last few things and release that version publicly

**Comment by cilipecos** [comment]
Thank you!
