### ISSUE TITLE
Parsing Error guild save

### ISSUE THREAD

**Issue by hugorodrigues12** [the-marenga/sf-api#82]
Hello, I was playing a little bit with the  api and when trying to get the game state I kept getting

`called `Result::unwrap()` on an `Err` value: ParsingError("guild save", "\"0F1E14050F051505050406\"")`

This is how I have it:
`let characters = account.characters().await.unwrap().into_iter().flatten();
    // println!("Account characters: {:?}", characters);

    for mut session in characters {
        // You can use the sessions, that the account returns like
        // a normal (logged out) session now
        let response = session.login().await.unwrap();
        // println!("Session: {:?}", response);
        let mut game_state = GameState::new(response).unwrap();
        println!("Character: {}", game_state.character.name);
        // println!("Character: {}", game_state.character.name);
    }`.

Btw,  I am very new to rust, only used it out of curiosity for your API.

**Comment by the-marenga** [comment]
The version on crates.io is broken, because of the last big server update. The in development version in this repo should however already contain fixes for your issue. You can use the latest version by changing the `sf-api` line in your `Cargo.toml` to 
```
sf-api = { git = "https://github.com/the-marenga/sf-api", rev = "79607d2" }
```
There is still a mismatch with the dungeon enemy levels, but otherwise this version should work without issues. If your error persists, feel free to let me know and I will have a deeper look into it

**Comment by hugorodrigues12** [comment]
Thanks for the quick followup. Changing to the latest version fixed the issue. Thank you for the help.
