### ISSUE TITLE
Unlockables & FortressBuildFinish don't seem to be working

### ISSUE THREAD

**Issue by al95la** [the-marenga/sf-api#85]
I've experienced this issue with the lvl 20 dungeon unlock. However, this might not be the only one that isn't working.

let unlocks: &Vec<Unlockables> = &gs.pending_unlocks.clone();
for x in unlocks{
  let result = session.send_command(Command::UnlockFeature { unlockable: *x }).await.unwrap();
}

results in an error message saying "feature is not unlockable".
To be precise, this error message only occurs when attempting it for the 2nd + time. 
The first unlock however does not seem to actually unlock the dungeon. Which is why the unlockable is not consumed and remains in the list of unlockables.

The unlockable in question is : Unlockable { main_ident: 30, sub_ident: 30 }

Also:

let result = session.send_command(Command::FortressBuildFinish { f_type: target, mushrooms: 0 }).await.unwrap();
does not seem to do anything.

Could you look into this please?

**Comment by the-marenga** [comment]
This is weird. The toilet has a special unlock command, but otherwise the unlocks are suposed to be trivial to handle. Can you confirm, that you are using the newest api version on git and the simplesession for this example code? And will this happen again, if you restart/retry this code, or is this just a temporary state, that fixes itself, once you login the session again/restart your program?

The FortressBuildFinish is certainly a bug on my part, I am going to fix this asap

**Comment by alexb231** [comment]
Tested with the latest version using SimpleSession and verified by running the example code to ensure accuracy. Here’s the observed behavior:

An unlockable item was obtained in my case: Unlockable { main_ident: 30, sub_ident: 30 } // representing a dungeon key.

On the first command execution, no SFError is triggered. After updating the GameState, the unlockable remains available. However, upon sending the command a second time, an SFError is returned, and the dungeon does not appear as unlocked in the UI.

Re-running the code repeats this cycle, with the same issue persisting. While this functionality seems to work as intended with the very first dungeon in the Lightworld, subsequent dungeons are not unlocking as expected.

**Comment by the-marenga** [comment]
Thanks! If I had to guess, I'd say the subident gets parsed incorrectly somewhere. I will have a look into that

**Comment by the-marenga** [comment]
Yeah, turns out I was using the ident as the subident. No idea, why this worked when I tested it originally. Might have been a refactoring bug after the initial testing. I don't have the time rn to make a new account and level it up until lvl 20 to make sure this works now, but I strongly suspect, that this will fix this issue

**Comment by alexb231** [comment]
Oh nvm you fixed it :D

**Comment by alexb231** [comment]
Tested it, works fine now thanks.

**Comment by the-marenga** [comment]
Thanks for testing 👍🏻
